[package]
name = "shabal-rs"
version = "0.1.0"
authors = ["bold <bold@cryptoguru.com>"]

[dependencies]
digest = "0.8"
block-buffer = "0.7"
opaque-debug = "0.2"

[dev-dependencies]
digest = { version = "0.8", features = ["dev"] }
hex-literal = "0.1"